batch_size: 1
epochs: 3
finetune_type: qlora
gradient_accumulation_steps: 16
log_with: tensorboard
lora_alpha: 32
lora_dropout: 0.1
lora_r: 8
lr: 0.0001
model_name_or_path: /home/asri/RAG-Retrieval/rag_retrieval/train/embedding/output/4500datas_summary20250601_epoch11-20_1e-4_losscheck/checkpoint-epoch-1/merge
neg_nums: 8
output_dir: /home/asri/EmbedRAG/train_output/8qlora0631
passage_max_len: 1000
quantization_bits: 8
query_max_len: 128
save_on_epoch_end: 1
seed: 42
temperature: 0.02
train_dataset: /home/asri/FlagEmbedding/bge_data_gen/data/1140606/tsd_feedback_data_be200_0606.jsonl
warmup_proportion: 0.05
